### ISSUE TITLE
CORS error (caused by rate limit error)

### ISSUE THREAD

**Issue by asportnoy** [Penguin-Spy/replugged-pronoundb#2] opened 2023-01-07 17:22 UTC
<img width="556" alt="Screenshot on 2023-01-07 at 11 21 38" src="https://user-images.githubusercontent.com/14863373/211162843-fff48ff4-a863-4ec3-bf51-3addd466ee3f.png">

**Comment by Penguin-Spy** [comment] 2023-01-12 06:57
rate limiting issue, i can fix this by using the bulk lookup endpoint (my initial implementation was lazy).
the CORS issue is caused by the 429 response not including the `access-control-allow-origin` header which is *super helpful*

**Comment by Penguin-Spy** [comment] 2023-01-13 06:57
fixed with 2ac7684, the plugin now uses the bulk lookup endpoint and properly handles 429, 500, and 503 response codes (retrying after the requested delay or 15 seconds)

**Closed by Penguin-Spy** 2023-01-13 06:57 UTC
Labels: bug, confirmed
